# Generated by Django 4.2.7 on 2024-01-20 10:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Conversation',
            new_name='Discussion',
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['sent_at']},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='conversation',
            new_name='discussion',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='date_creation',
            new_name='sent_at',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='utilisateur',
            new_name='user',
        ),
    ]
