# Generated by Django 4.2.7 on 2024-01-20 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_conversation_discussion_alter_message_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discussion',
            old_name='participants',
            new_name='users',
        ),
    ]
