# Generated by Django 4.2.7 on 2024-01-23 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_participants_discussion_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message',
            new_name='content',
        ),
    ]
