# Generated by Django 5.1 on 2024-08-26 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_nextconference'),
    ]

    operations = [
        migrations.AddField(
            model_name='nextconference',
            name='programme',
            field=models.FileField(blank=True, null=True, upload_to='programmes/'),
        ),
    ]
