# Generated by Django 5.1 on 2024-08-26 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_nextconference_programme'),
    ]

    operations = [
        migrations.AddField(
            model_name='nextconference',
            name='image',
            field=models.ImageField(default='Image1.jpg', upload_to='conferences/images/'),
        ),
        migrations.AlterField(
            model_name='nextconference',
            name='programme',
            field=models.FileField(blank=True, null=True, upload_to='conferences/programmes/'),
        ),
    ]
