# Generated by Django 5.1 on 2024-08-26 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_nextconference_image_alter_nextconference_programme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nextconference',
            name='image',
            field=models.ImageField(default='conferences/images/image002.jpg', upload_to='conferences/images/'),
        ),
    ]
