# Generated by Django 5.1 on 2024-08-26 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_nextconference_link_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActOfTheDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('acte', models.FileField(upload_to='acts/files/')),
                ('date', models.DateField()),
            ],
        ),
    ]
