# Generated by Django 5.1 on 2024-08-26 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_actofthedays'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actofthedays',
            old_name='acte',
            new_name='act',
        ),
    ]
