# Generated by Django 5.1 on 2024-08-26 23:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_rename_acte_actofthedays_act'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actofthedays',
            name='date',
        ),
        migrations.AddField(
            model_name='actofthedays',
            name='year',
            field=models.PositiveIntegerField(default=2024, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2024)]),
        ),
    ]
