# Generated by Django 5.1 on 2024-08-26 23:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_actofthedays_date_actofthedays_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actofthedays',
            old_name='act',
            new_name='file',
        ),
        migrations.AlterField(
            model_name='actofthedays',
            name='year',
            field=models.PositiveIntegerField(default=2024, validators=[django.core.validators.MinValueValidator(2011), django.core.validators.MaxValueValidator(2024)]),
        ),
    ]
