# Generated by Django 5.1 on 2024-08-29 22:00

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_rename_act_actofthedays_file_alter_actofthedays_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinksCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UsefullLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='actofthedays',
            name='file',
            field=models.FileField(upload_to=main.models.upload_to),
        ),
    ]
