# Generated by Django 5.1 on 2024-08-29 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_linkscategories_usefulllinks_alter_actofthedays_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='usefulllinks',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.linkscategories'),
        ),
    ]
