# Generated by Django 5.1 on 2024-08-30 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_usefulllinks_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningResources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('file', models.FileField(blank=True, null=True, upload_to='learning-ressources/')),
            ],
        ),
    ]
