# Generated by Django 4.2.7 on 2024-09-25 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_learningresources_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='CAFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='ca_files/')),
            ],
        ),
    ]
