# Generated by Django 5.1 on 2024-10-14 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_learningresources_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nextconference',
            name='programme',
        ),
        migrations.AddField(
            model_name='nextconference',
            name='link_program',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nextconference',
            name='program',
            field=models.FileField(blank=True, null=True, upload_to='conferences/programs/'),
        ),
        migrations.AlterField(
            model_name='nextconference',
            name='link_form',
            field=models.URLField(blank=True, max_length=100),
        ),
    ]
