# Generated by Django 5.1 on 2024-10-14 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_nextconference_programme_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nextconference',
            name='link_program',
        ),
        migrations.RemoveField(
            model_name='nextconference',
            name='program',
        ),
        migrations.AddField(
            model_name='nextconference',
            name='programme',
            field=models.FileField(blank=True, null=True, upload_to='conferences/programmes/'),
        ),
        migrations.AlterField(
            model_name='nextconference',
            name='link_form',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
