# Generated by Django 5.1 on 2024-11-01 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_cafile'),
        ('main', '0020_remove_nextconference_link_program_and_more'),
    ]

    operations = [
    ]
