# Generated by Django 5.1 on 2024-11-01 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_meeting_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nextconference',
            name='image',
            field=models.ImageField(default='conferences/images/default.png', upload_to='conferences/images/'),
        ),
    ]
